<a href="https://colab.research.google.com/github/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Programming/blob/main/RBSN_DSAPR26_Pandas_Lab_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import needed library
import pandas as pd

In [3]:
# Set file location
fileLocation = "https://github.com/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Proramming/blob/main/SalesData.xlsx?raw=true"

In [4]:
# Connect to and load data from a file
# Example: .XLSX file
dfRaw = pd.read_excel(fileLocation)

In [5]:
# Preview the top 5 rows of the loaded data
dfRaw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
4,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850,United Kingdom

In [6]:
# Connect to and load clean data from a file
# Example: .XLSX file
ignoreRows = 4
dfClean = pd.read_excel(fileLocation, skiprows= ignoreRows)
dfClean.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-01-12 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom

In [7]:
# Check dataframe shape
dfClean.shape

(541823, 8)

In [8]:
# Check RAM consumption
x = dfClean.memory_usage().sum()

# Smarter display in MB
result = x / 1000000
print(f"RAM consumption: {result:.2f} MB")

RAM consumption: 34.68 MB

In [9]:
# Preview the last 5 rows of the loaded data
dfClean.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541818,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-09-12 12:50:00,0.85,12680.0,France
541819,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-09-12 12:50:00,2.10,12680.0,France
541820,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-09-12 12:50:00,4.15,12680.0,France
541821,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-09-12 12:50:00,4.15,12680.0,France
541822,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-09-12 12:50:00,4.95,12680.0,France

In [10]:
# Preview the top n rows of the loaded data
n = 3
dfClean.head(n)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-01-12 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-01-12 08:26:00,2.75,17850.0,United Kingdom

In [11]:
# Preview the last n rows of the loaded data
n = 3
dfClean.tail(n)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541820,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-09-12 12:50:00,4.15,12680.0,France
541821,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-09-12 12:50:00,4.15,12680.0,France
541822,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-09-12 12:50:00,4.95,12680.0,France

In [12]:
# Preview a sample row from the loaded data
dfClean.sample()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
470595,576618,21028,NINJA RABBIT BLACK,1,15-11-2011 17:00,2.46,NaN,United Kingdom

In [13]:
# Preview sample n rows of the loaded data
n = 7
dfClean.sample(n)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
150798,549524,22740,POLKADOT PEN,11,2011-08-04 15:42:00,1.63,NaN,United Kingdom
185819,552826,21668,RED STRIPE CERAMIC DRAWER KNOB,12,2011-11-05 13:20:00,1.25,14277.0,France
304575,563585,22961,JAM MAKING SET PRINTED,1,17-08-2011 17:01,1.45,17070.0,United Kingdom
504132,578942,20751,FUNKY WASHING UP GLOVES ASSORTED,1,27-11-2011 13:29,2.10,17288.0,United Kingdom
362546,568505,22686,FRENCH BLUE METAL DOOR SIGN No,2,27-09-2011 12:17,1.25,15311.0,United Kingdom
94761,544409,22993,SET OF 4 PANTRY JELLY MOULDS,12,18-02-2011 13:32,1.25,16265.0,United Kingdom
19553,537868,84375,SET OF 20 KIDS COOKIE CUTTERS,24,2010-08-12 16:49:00,2.10,12433.0,Norway

In [14]:
# Get the shape of the dataframe (rows and columns)
dfClean.shape

(541823, 8)