<a href="https://colab.research.google.com/github/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Programming/blob/main/RBSN_DSAPR26_Pandas_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import needed library
import pandas as pd

In [2]:
# Set file location
fileLocation = "https://github.com/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Proramming/blob/main/world-population-by-country-2020.json?raw=true"

In [3]:
# Connect to and load data from a file
# Example: .JSON file
df1 = pd.read_json(fileLocation)

In [4]:
# Preview the top 5 rows of the loaded data
df1.head()

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %
2,3,United States,"331,002,651",0.59 %,"1,937,734",36,"9,147,420","954,806",1.8,38,83 %,4.25 %
3,4,Indonesia,"273,523,615",1.07 %,"2,898,047",151,"1,811,570","-98,955",2.3,30,56 %,3.51 %
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %,2.83 %

In [ ]:
# Preview the last 5 rows of the loaded data
df1.tail()

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
230,231,Montserrat,"4,992",0.06 %,3,50,100,,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,"3,480",3.05 %,103,0,"12,170",,N.A.,N.A.,66 %,0.00 %
232,233,Niue,"1,626",0.68 %,11,6,260,,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,"1,357",1.27 %,17,136,10,,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,"2,003",0,,N.A.,N.A.,N.A.,0.00 %

In [ ]:
# Preview the top n rows of the loaded data
n = 3
df1.head(n)

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %
2,3,United States,"331,002,651",0.59 %,"1,937,734",36,"9,147,420","954,806",1.8,38,83 %,4.25 %

In [ ]:
# Preview the last n rows of the loaded data
n = 3
df1.tail(n)

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
232,233,Niue,"1,626",0.68 %,11,6,260,,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,"1,357",1.27 %,17,136,10,,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,"2,003",0,,N.A.,N.A.,N.A.,0.00 %

In [ ]:
# Preview a sample row from the loaded data
df1.sample()

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
228,229,Saint Helena,"6,077",0.30 %,18,16,390,,N.A.,N.A.,27 %,0.00 %

In [ ]:
# Preview sample n rows of the loaded data
n = 7
df1.sample(n)

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
201,202,Isle of Man,"85,033",0.53 %,449,149,570,,N.A.,N.A.,53 %,0.00 %
191,192,Curaçao,"164,093",0.41 %,669,370,444,515,1.8,42,89 %,0.00 %
93,94,Hungary,"9,660,351",-0.25 %,"-24,328",107,"90,530","6,000",1.5,43,72 %,0.12 %
26,27,Kenya,"53,771,296",2.28 %,"1,197,323",94,"569,140","-10,000",3.5,20,28 %,0.69 %
227,228,Saint Barthelemy,"9,877",0.30 %,30,470,21,,N.A.,N.A.,0 %,0.00 %
85,86,Czech Republic (Czechia),"10,708,981",0.18 %,"19,772",139,"77,240","22,011",1.6,43,74 %,0.14 %
178,179,Martinique,"375,265",-0.08 %,-289,354,"1,060",-960,1.9,47,92 %,0.00 %

In [ ]:
# Get the shape of the dataframe (rows and columns)
df1.shape

(235, 12)