<a href="https://colab.research.google.com/github/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Programming/blob/main/RBSN_DSAPR26_Pandas_Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import needed library
import pandas as pd

In [2]:
# Set file location
fileLocation = "https://www.bbc.com/sport/football/tables"

In [4]:
# Connect to and load data from a file
# Example: .HTML file
dfRaw = pd.read_html(fileLocation)

In [5]:
len(dfRaw)

8

In [6]:
dfRaw[0]

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,"Form, Last 6 games, Oldest first"
0,1Arsenal,37,25,7,5,69,26,43,82,LResult LossLResult LossWResult WinWResult Win...
1,2Manchester City,37,23,9,5,76,33,43,78,WResult WinWResult WinDResult DrawWResult WinW...
2,3Manchester United,37,19,11,7,66,50,16,68,LResult LossWResult WinWResult WinWResult WinD...
3,4Aston Villa,37,18,8,11,54,48,6,62,DResult DrawWResult WinLResult LossLResult Los...
4,5Liverpool,37,17,8,12,62,52,10,59,WResult WinWResult WinWResult WinLResult LossD...
5,6AFC Bournemouth,37,13,17,7,57,53,4,56,WResult WinWResult WinDResult DrawWResult WinW...
6,7Brighton & Hove Albion,37,14,11,12,52,43,9,53,WResult WinDResult DrawWResult WinLResult Loss...
7,8Chelsea,37,14,10,13,57,50,7,52,LResult LossLResult LossLResult LossLResult Lo...
8,9Brentford,37,14,10,13,54,51,3,52,DResult DrawDResult DrawLResult LossWResult Wi...
9,10Sunderland,37,13,12,12,40,47,-7,51,WResult WinLResult LossLResult LossDResult Dra...
10,11Newcastle United,37,14,7,16,53,53,0,49,LResult LossLResult LossLResult LossWResult Wi...
11,12Everton,37,13,10,14,47,49,-2,49,DResult DrawLResult LossLResult LossDResult Dr...
12,13Fulham,37,14,7,16,45,51,-6,49,LResult LossDResult DrawWResult WinLResult Los...
13,14Leeds United,37,11,14,12,49,53,-4,47,WResult WinWResult WinDResult DrawWResult WinD...
14,15Crystal Palace,37,11,12,14,40,49,-9,45,DResult DrawLResult LossLResult LossDResult Dr...
15,16Nottingham Forest,37,11,10,16,47,50,-3,43,DResult DrawWResult WinWResult WinWResult WinD...
16,17Tottenham Hotspur,37,9,11,17,47,57,-10,38,LResult LossDResult DrawWResult WinWResult Win...
17,18West Ham United,37,9,9,19,43,65,-22,36,WResult WinDResult DrawWResult WinLResult Loss...
18,19Burnley,37,4,9,24,37,74,-37,21,LResult LossLResult LossLResult LossLResult Lo...
19,20Wolverhampton Wanderers,37,3,10,24,26,67,-41,19,LResult LossLResult LossLResult LossDResult Dr...

In [ ]:
dfEPL = dfRaw[0]

In [ ]:
# Preview the top 5 rows of the loaded data
dfEPL.head()

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,"Form, Last 6 games, Oldest first"
0,1Arsenal,37,25,7,5,69,26,43,82,LResult LossLResult LossWResult WinWResult Win...
1,2Manchester City,37,23,9,5,76,33,43,78,WResult WinWResult WinDResult DrawWResult WinW...
2,3Manchester United,37,19,11,7,66,50,16,68,LResult LossWResult WinWResult WinWResult WinD...
3,4Aston Villa,37,18,8,11,54,48,6,62,DResult DrawWResult WinLResult LossLResult Los...
4,5Liverpool,37,17,8,12,62,52,10,59,WResult WinWResult WinWResult WinLResult LossD...

In [ ]:
# Preview the last 5 rows of the loaded data
dfEPL.tail()

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,"Form, Last 6 games, Oldest first"
15,16Nottingham Forest,37,11,10,16,47,50,-3,43,DResult DrawWResult WinWResult WinWResult WinD...
16,17Tottenham Hotspur,37,9,11,17,47,57,-10,38,LResult LossDResult DrawWResult WinWResult Win...
17,18West Ham United,37,9,9,19,43,65,-22,36,WResult WinDResult DrawWResult WinLResult Loss...
18,19Burnley,37,4,9,24,37,74,-37,21,LResult LossLResult LossLResult LossLResult Lo...
19,20Wolverhampton Wanderers,37,3,10,24,26,67,-41,19,LResult LossLResult LossLResult LossDResult Dr...

In [ ]:
# Preview the top n rows of the loaded data
n = 3
dfEPL.head(n)

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,"Form, Last 6 games, Oldest first"
0,1Arsenal,37,25,7,5,69,26,43,82,LResult LossLResult LossWResult WinWResult Win...
1,2Manchester City,37,23,9,5,76,33,43,78,WResult WinWResult WinDResult DrawWResult WinW...
2,3Manchester United,37,19,11,7,66,50,16,68,LResult LossWResult WinWResult WinWResult WinD...

In [ ]:
# Preview the last n rows of the loaded data
n = 3
dfEPL.tail(n)

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,"Form, Last 6 games, Oldest first"
17,18West Ham United,37,9,9,19,43,65,-22,36,WResult WinDResult DrawWResult WinLResult Loss...
18,19Burnley,37,4,9,24,37,74,-37,21,LResult LossLResult LossLResult LossLResult Lo...
19,20Wolverhampton Wanderers,37,3,10,24,26,67,-41,19,LResult LossLResult LossLResult LossDResult Dr...

In [ ]:
# Preview a sample row from the loaded data
dfEPL.sample()

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,"Form, Last 6 games, Oldest first"
10,11Newcastle United,37,14,7,16,53,53,0,49,LResult LossLResult LossLResult LossWResult Wi...

In [ ]:
# Preview sample n rows of the loaded data
n = 7
dfEPL.sample(n)

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,"Form, Last 6 games, Oldest first"
4,5Liverpool,37,17,8,12,62,52,10,59,WResult WinWResult WinWResult WinLResult LossD...
0,1Arsenal,37,25,7,5,69,26,43,82,LResult LossLResult LossWResult WinWResult Win...
16,17Tottenham Hotspur,37,9,11,17,47,57,-10,38,LResult LossDResult DrawWResult WinWResult Win...
10,11Newcastle United,37,14,7,16,53,53,0,49,LResult LossLResult LossLResult LossWResult Wi...
17,18West Ham United,37,9,9,19,43,65,-22,36,WResult WinDResult DrawWResult WinLResult Loss...
3,4Aston Villa,37,18,8,11,54,48,6,62,DResult DrawWResult WinLResult LossLResult Los...
9,10Sunderland,37,13,12,12,40,47,-7,51,WResult WinLResult LossLResult LossDResult Dra...

In [ ]:
# Get the shape of the dataframe (rows and columns)
dfEPL.shape

(20, 10)

In [ ]:
# Check available columns
dfEPL.columns

Index(['Team', 'Played', 'Won', 'Drawn', 'Lost', 'Goals For', 'Goals Against',
       'Goal Difference', 'Points', 'Form, Last 6 games, Oldest first'],
      dtype='object')

In [ ]:
# Clean up EPL table
neededHeaders = ['Team', 'Played', 'Won', 'Drawn', 'Lost', 'Goals For', 'Goals Against',
       'Goal Difference', 'Points']

dfEPL = dfEPL[neededHeaders]
dfEPL

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points
0,1Arsenal,37,25,7,5,69,26,43,82
1,2Manchester City,37,23,9,5,76,33,43,78
2,3Manchester United,37,19,11,7,66,50,16,68
3,4Aston Villa,37,18,8,11,54,48,6,62
4,5Liverpool,37,17,8,12,62,52,10,59
5,6AFC Bournemouth,37,13,17,7,57,53,4,56
6,7Brighton & Hove Albion,37,14,11,12,52,43,9,53
7,8Chelsea,37,14,10,13,57,50,7,52
8,9Brentford,37,14,10,13,54,51,3,52
9,10Sunderland,37,13,12,12,40,47,-7,51
10,11Newcastle United,37,14,7,16,53,53,0,49
11,12Everton,37,13,10,14,47,49,-2,49
12,13Fulham,37,14,7,16,45,51,-6,49
13,14Leeds United,37,11,14,12,49,53,-4,47
14,15Crystal Palace,37,11,12,14,40,49,-9,45
15,16Nottingham Forest,37,11,10,16,47,50,-3,43
16,17Tottenham Hotspur,37,9,11,17,47,57,-10,38
17,18West Ham United,37,9,9,19,43,65,-22,36
18,19Burnley,37,4,9,24,37,74,-37,21
19,20Wolverhampton Wanderers,37,3,10,24,26,67,-41,19

In [ ]:
# Extract the 1st chracter in data series Team into data series Rank
dfEPL['Rank'] = dfEPL['Team'].str[0]
dfEPL

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,Rank
0,1Arsenal,37,25,7,5,69,26,43,82,1
1,2Manchester City,37,23,9,5,76,33,43,78,2
2,3Manchester United,37,19,11,7,66,50,16,68,3
3,4Aston Villa,37,18,8,11,54,48,6,62,4
4,5Liverpool,37,17,8,12,62,52,10,59,5
5,6AFC Bournemouth,37,13,17,7,57,53,4,56,6
6,7Brighton & Hove Albion,37,14,11,12,52,43,9,53,7
7,8Chelsea,37,14,10,13,57,50,7,52,8
8,9Brentford,37,14,10,13,54,51,3,52,9
9,10Sunderland,37,13,12,12,40,47,-7,51,1
10,11Newcastle United,37,14,7,16,53,53,0,49,1
11,12Everton,37,13,10,14,47,49,-2,49,1
12,13Fulham,37,14,7,16,45,51,-6,49,1
13,14Leeds United,37,11,14,12,49,53,-4,47,1
14,15Crystal Palace,37,11,12,14,40,49,-9,45,1
15,16Nottingham Forest,37,11,10,16,47,50,-3,43,1
16,17Tottenham Hotspur,37,9,11,17,47,57,-10,38,1
17,18West Ham United,37,9,9,19,43,65,-22,36,1
18,19Burnley,37,4,9,24,37,74,-37,21,1
19,20Wolverhampton Wanderers,37,3,10,24,26,67,-41,19,2

In [ ]:
# Remove trailing numbers from data series Team
dfEPL['Team'] = dfEPL['Team'].str[1:]
dfEPL

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,Rank
0,Arsenal,37,25,7,5,69,26,43,82,1
1,Manchester City,37,23,9,5,76,33,43,78,2
2,Manchester United,37,19,11,7,66,50,16,68,3
3,Aston Villa,37,18,8,11,54,48,6,62,4
4,Liverpool,37,17,8,12,62,52,10,59,5
5,AFC Bournemouth,37,13,17,7,57,53,4,56,6
6,Brighton & Hove Albion,37,14,11,12,52,43,9,53,7
7,Chelsea,37,14,10,13,57,50,7,52,8
8,Brentford,37,14,10,13,54,51,3,52,9
9,0Sunderland,37,13,12,12,40,47,-7,51,1
10,1Newcastle United,37,14,7,16,53,53,0,49,1
11,2Everton,37,13,10,14,47,49,-2,49,1
12,3Fulham,37,14,7,16,45,51,-6,49,1
13,4Leeds United,37,11,14,12,49,53,-4,47,1
14,5Crystal Palace,37,11,12,14,40,49,-9,45,1
15,6Nottingham Forest,37,11,10,16,47,50,-3,43,1
16,7Tottenham Hotspur,37,9,11,17,47,57,-10,38,1
17,8West Ham United,37,9,9,19,43,65,-22,36,1
18,9Burnley,37,4,9,24,37,74,-37,21,1
19,0Wolverhampton Wanderers,37,3,10,24,26,67,-41,19,2

In [ ]:
# Remove trailing numbers from data series Team starting from row index 9
dfEPL.loc[9:, 'Team'] = dfEPL.loc[9:, 'Team'].str[1:]
dfEPL

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,Rank
0,Arsenal,37,25,7,5,69,26,43,82,1
1,Manchester City,37,23,9,5,76,33,43,78,2
2,Manchester United,37,19,11,7,66,50,16,68,3
3,Aston Villa,37,18,8,11,54,48,6,62,4
4,Liverpool,37,17,8,12,62,52,10,59,5
5,AFC Bournemouth,37,13,17,7,57,53,4,56,6
6,Brighton & Hove Albion,37,14,11,12,52,43,9,53,7
7,Chelsea,37,14,10,13,57,50,7,52,8
8,Brentford,37,14,10,13,54,51,3,52,9
9,Sunderland,37,13,12,12,40,47,-7,51,1
10,Newcastle United,37,14,7,16,53,53,0,49,1
11,Everton,37,13,10,14,47,49,-2,49,1
12,Fulham,37,14,7,16,45,51,-6,49,1
13,Leeds United,37,11,14,12,49,53,-4,47,1
14,Crystal Palace,37,11,12,14,40,49,-9,45,1
15,Nottingham Forest,37,11,10,16,47,50,-3,43,1
16,Tottenham Hotspur,37,9,11,17,47,57,-10,38,1
17,West Ham United,37,9,9,19,43,65,-22,36,1
18,Burnley,37,4,9,24,37,74,-37,21,1
19,Wolverhampton Wanderers,37,3,10,24,26,67,-41,19,2

In [ ]:
# Update data series Rank to use values in data series Points in ascending order
dfEPL['Rank'] = dfEPL['Points'].rank(method='min', ascending=False).astype(int)
dfEPL

,Team,Played,Won,Drawn,Lost,Goals For,Goals Against,Goal Difference,Points,Rank
0,Arsenal,37,25,7,5,69,26,43,82,1
1,Manchester City,37,23,9,5,76,33,43,78,2
2,Manchester United,37,19,11,7,66,50,16,68,3
3,Aston Villa,37,18,8,11,54,48,6,62,4
4,Liverpool,37,17,8,12,62,52,10,59,5
5,AFC Bournemouth,37,13,17,7,57,53,4,56,6
6,Brighton & Hove Albion,37,14,11,12,52,43,9,53,7
7,Chelsea,37,14,10,13,57,50,7,52,8
8,Brentford,37,14,10,13,54,51,3,52,8
9,Sunderland,37,13,12,12,40,47,-7,51,10
10,Newcastle United,37,14,7,16,53,53,0,49,11
11,Everton,37,13,10,14,47,49,-2,49,11
12,Fulham,37,14,7,16,45,51,-6,49,11
13,Leeds United,37,11,14,12,49,53,-4,47,14
14,Crystal Palace,37,11,12,14,40,49,-9,45,15
15,Nottingham Forest,37,11,10,16,47,50,-3,43,16
16,Tottenham Hotspur,37,9,11,17,47,57,-10,38,17
17,West Ham United,37,9,9,19,43,65,-22,36,18
18,Burnley,37,4,9,24,37,74,-37,21,19
19,Wolverhampton Wanderers,37,3,10,24,26,67,-41,19,20