<a href="https://colab.research.google.com/github/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Programming/blob/main/RBSN_DSAPR26_Pandas_Lab_Master.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import needed library
import pandas as pd

In [2]:
# Set file location
fileLocation = "https://github.com/IbrahimHammed/RBSN-MSc-Data-Science-2026-Python-Proramming/blob/main/customer_segmentation_data.csv?raw=true"

In [3]:
# Basic Example: .CSV file
# Connect to and load everything from a file
dfRaw = pd.read_csv(fileLocation)

In [4]:
# Check the dimension of the dataframe
dfRaw.shape

(53503, 20)

In [5]:
# Preview the top 5 rows of the loaded data
dfRaw.head()

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,Chat,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2

In [6]:
# Basic Example: .CSV file
# Connect to and load desired columns from a file
relevantColumns = ["Customer ID", "Age", "Gender", "Marital Status", "Occupation", "Income Level", "Purchase History", "Coverage Amount", "Premium Amount", "Customer Preferences"]
dfSummarised = pd.read_csv(fileLocation, usecols = relevantColumns)

In [7]:
dfSummarised.head()

,Customer ID,Age,Gender,Marital Status,Occupation,Income Level,Purchase History,Coverage Amount,Premium Amount,Customer Preferences
0,84966,23,Female,Married,Entrepreneur,70541,04-10-2018,366603,2749,Email
1,95568,26,Male,Widowed,Manager,54168,11-06-2018,780236,1966,Mail
2,10544,29,Female,Single,Entrepreneur,73899,06-05-2021,773926,4413,Email
3,77033,20,Male,Divorced,Entrepreneur,63381,09-02-2018,787815,4342,Text
4,88160,25,Female,Separated,Manager,38794,09-10-2018,366506,1276,Email

In [8]:
# Basic Example: .CSV file
# Connect to and load desired columns from a file
relevantColumns = ["Customer ID", "Age", "Gender", "Marital Status", "Occupation", "Income Level", "Purchase History", "Coverage Amount", "Premium Amount", "Customer Preferences"]
dfSummarised = pd.read_csv(fileLocation, usecols = relevantColumns)

# Set the number of rows needed
desiredRowCount = 1000

# Load data rows into a dataframe
dfFiltered = pd.read_csv(fileLocation, usecols = relevantColumns, nrows = desiredRowCount )

In [9]:
dfFiltered.shape

(1000, 10)

In [10]:
dfFiltered.head()

,Customer ID,Age,Gender,Marital Status,Occupation,Income Level,Purchase History,Coverage Amount,Premium Amount,Customer Preferences
0,84966,23,Female,Married,Entrepreneur,70541,04-10-2018,366603,2749,Email
1,95568,26,Male,Widowed,Manager,54168,11-06-2018,780236,1966,Mail
2,10544,29,Female,Single,Entrepreneur,73899,06-05-2021,773926,4413,Email
3,77033,20,Male,Divorced,Entrepreneur,63381,09-02-2018,787815,4342,Text
4,88160,25,Female,Separated,Manager,38794,09-10-2018,366506,1276,Email

In [11]:
# Back to dfRaw
dfRaw.shape

(53503, 20)

In [12]:
# View available columns
dfRaw.columns

Index(['Customer ID', 'Age', 'Gender', 'Marital Status', 'Education Level',
       'Geographic Information', 'Occupation', 'Income Level',
       'Behavioral Data', 'Purchase History',
       'Interactions with Customer Service', 'Insurance Products Owned',
       'Coverage Amount', 'Premium Amount', 'Policy Type',
       'Customer Preferences', 'Preferred Communication Channel',
       'Preferred Contact Time', 'Preferred Language', 'Segmentation Group'],
      dtype='object')

In [13]:
# Preview the top 5 rows of the loaded data
dfRaw.head()

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,Chat,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2

In [14]:
# Preview the last 5 rows of the loaded data
dfRaw.tail()

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
53498,44809,35,Female,Divorced,Associate Degree,Andaman and Nicobar Islands,Salesperson,120850,policy3,01-01-2019,Mobile App,policy1,586401,4404,Family,In-Person Meeting,Phone,Afternoon,German,Segment5
53499,65485,61,Male,Single,Doctorate,Himachal Pradesh,Entrepreneur,122309,policy5,5/18/2021,Mobile App,policy4,637733,1285,Group,Text,Mail,Afternoon,German,Segment1
53500,26213,25,Male,Divorced,Doctorate,Assam,Teacher,49258,policy2,11/27/2018,In-Person,policy1,631057,4407,Individual,Text,Text,Weekends,French,Segment4
53501,63136,42,Male,Married,Doctorate,Andhra Pradesh,Artist,66301,policy4,06-04-2021,In-Person,policy1,730385,4482,Business,Mail,Phone,Morning,French,Segment5
53502,62125,20,Male,Divorced,Doctorate,Daman and Diu,Salesperson,136632,policy2,10/14/2022,Phone,policy1,743262,4499,Group,Text,In-Person Meeting,Evening,German,Segment2

In [15]:
# Preview the top n rows of the loaded data
n = 3
dfRaw.head(n)

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3

In [16]:
# Preview the last n rows of the loaded data
n = 3
dfRaw.tail(n)

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
53500,26213,25,Male,Divorced,Doctorate,Assam,Teacher,49258,policy2,11/27/2018,In-Person,policy1,631057,4407,Individual,Text,Text,Weekends,French,Segment4
53501,63136,42,Male,Married,Doctorate,Andhra Pradesh,Artist,66301,policy4,06-04-2021,In-Person,policy1,730385,4482,Business,Mail,Phone,Morning,French,Segment5
53502,62125,20,Male,Divorced,Doctorate,Daman and Diu,Salesperson,136632,policy2,10/14/2022,Phone,policy1,743262,4499,Group,Text,In-Person Meeting,Evening,German,Segment2

In [17]:
# Preview a sample row from the loaded data
dfRaw.sample()

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
12491,12448,30,Male,Separated,Associate Degree,Chhattisgarh,Salesperson,71084,policy2,8/26/2018,Chat,policy3,346812,4500,Individual,Email,Email,Evening,German,Segment5

In [18]:
# Preview sample n rows of the loaded data
n = 7
dfRaw.sample(n)

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
32532,26637,61,Male,Single,Associate Degree,Dadra and Nagar Haveli,Lawyer,50258,policy2,3/21/2019,Chat,policy5,973467,4486,Group,In-Person Meeting,In-Person Meeting,Evening,German,Segment4
37715,67176,27,Male,Separated,Bachelor's Degree,Haryana,Engineer,113530,policy1,7/25/2019,Chat,policy4,973349,4927,Individual,In-Person Meeting,Text,Afternoon,Spanish,Segment2
49160,44084,63,Female,Widowed,High School Diploma,Meghalaya,Entrepreneur,135435,policy5,07-08-2020,Chat,policy2,140117,3839,Group,Email,Phone,Anytime,English,Segment5
43227,95739,25,Male,Married,Bachelor's Degree,Uttar Pradesh,Entrepreneur,57648,policy2,01-06-2020,Phone,policy1,692978,3733,Group,In-Person Meeting,Email,Morning,Spanish,Segment2
972,89051,51,Male,Single,Associate Degree,Lakshadweep,Salesperson,115158,policy5,5/20/2023,Mobile App,policy2,306509,4200,Group,Email,Text,Anytime,French,Segment5
12763,3378,24,Male,Widowed,Doctorate,Arunachal Pradesh,Manager,130922,policy1,06-08-2021,Chat,policy3,667720,3868,Business,Phone,In-Person Meeting,Morning,French,Segment1
37682,4868,56,Female,Married,Master's Degree,Telangana,Artist,38717,policy4,08-05-2021,In-Person,policy1,494106,4537,Business,Text,Phone,Weekends,German,Segment2

In [19]:
# Get the shape of the dataframe (rows and columns)
dfRaw.shape

(53503, 20)

In [20]:
dfRaw.describe()

,Customer ID,Age,Income Level,Coverage Amount,Premium Amount
count,53503.000000,53503.000000,53503.000000,53503.000000,53503.000000
mean,52265.204998,44.140945,82768.324318,492580.789638,3023.702447
std,28165.000067,15.079486,36651.075670,268405.505571,1285.834295
min,1.000000,18.000000,20001.000000,50001.000000,500.000000
25%,28950.500000,32.000000,51568.500000,249613.500000,1817.000000
50%,55858.000000,43.000000,80719.000000,477261.000000,3194.000000
75%,76096.000000,57.000000,115973.500000,739124.000000,4311.500000
max,100000.000000,70.000000,149999.000000,1000000.000000,5000.000000

In [21]:
dfRaw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53503 entries, 0 to 53502
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Customer ID                         53503 non-null  int64
 1   Age                                 53503 non-null  int64
 2   Gender                              53503 non-null  object
 3   Marital Status                      53503 non-null  object
 4   Education Level                     53503 non-null  object
 5   Geographic Information              53503 non-null  object
 6   Occupation                          53503 non-null  object
 7   Income Level                        53503 non-null  int64
 8   Behavioral Data                     53503 non-null  object
 9   Purchase History                    53503 non-null  object
 10  Interactions with Customer Service  53503 non-null  object
 11  Insurance Products Owned            53503 non-null  object
 12  Coverage Amount                     53503 non-null  int64
 13  Premium Amount                      53503 non-null  int64
 14  Policy Type                         53503 non-null  object
 15  Customer Preferences                53503 non-null  object
 16  Preferred Communication Channel     53503 non-null  object
 17  Preferred Contact Time              53503 non-null  object
 18  Preferred Language                  53503 non-null  object
 19  Segmentation Group                  53503 non-null  object
dtypes: int64(5), object(15)
memory usage: 8.2+ MB

In [22]:
# Check RAM usage
result = dfRaw.memory_usage().sum()

# Format this in MB
print(f"{result / 1000000:.2f} MB")

8.56 MB

In [23]:
# Loop through the columns and change any column of object type to string data type
for col in dfRaw.columns:
    if dfRaw[col].dtype == 'object':
        dfRaw[col] = dfRaw[col].astype('string')

In [24]:
# Display info about the drataframe again for verification
dfRaw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53503 entries, 0 to 53502
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Customer ID                         53503 non-null  int64
 1   Age                                 53503 non-null  int64
 2   Gender                              53503 non-null  string
 3   Marital Status                      53503 non-null  string
 4   Education Level                     53503 non-null  string
 5   Geographic Information              53503 non-null  string
 6   Occupation                          53503 non-null  string
 7   Income Level                        53503 non-null  int64
 8   Behavioral Data                     53503 non-null  string
 9   Purchase History                    53503 non-null  string
 10  Interactions with Customer Service  53503 non-null  string
 11  Insurance Products Owned            53503 non-null  string
 12  Coverage Amount                     53503 non-null  int64
 13  Premium Amount                      53503 non-null  int64
 14  Policy Type                         53503 non-null  string
 15  Customer Preferences                53503 non-null  string
 16  Preferred Communication Channel     53503 non-null  string
 17  Preferred Contact Time              53503 non-null  string
 18  Preferred Language                  53503 non-null  string
 19  Segmentation Group                  53503 non-null  string
dtypes: int64(5), string(15)
memory usage: 8.2 MB

In [25]:
# Preview the data
dfRaw.head()

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,Chat,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2

In [26]:
# Change column headers by removing space between column header words
dfRaw.columns = ['CustomerID', 'Age', 'Gender', 'MaritalStatus', 'EducationLevel', 'Location', 'Occupation', 'IncomeLevel', 'BehavioralData', 'PurchaseHistory', 'CCChannel', 'PolicyOwned', 'CoverageAmount', 'PremiumAmount', 'PolicyType', 'CustomerPreferences', 'PreferredChannel', 'PreferredContactTime', 'PreferredLanguage', 'SegmentationGroup']
dfRaw.head()

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,CCChannel,PolicyOwned,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,Chat,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2

In [27]:
# Check distinct values in a column
dfRaw['Gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: string

In [28]:
dfRaw.MaritalStatus.unique()

<StringArray>
['Married', 'Widowed', 'Single', 'Divorced', 'Separated']
Length: 5, dtype: string

In [29]:
dfRaw.IncomeLevel.unique()

array([ 70541,  54168,  73899, ..., 122309,  49258,  66301])

In [30]:
# Summarise columns by count of values
dfRaw.Gender.value_counts()

Gender
Male      27499
Female    26004
Name: count, dtype: Int64

In [31]:
dfRaw['Gender'].value_counts()

Gender
Male      27499
Female    26004
Name: count, dtype: Int64

In [32]:
dfRaw.MaritalStatus.value_counts()

MaritalStatus
Married      13219
Divorced     13151
Single        9195
Widowed       9077
Separated     8861
Name: count, dtype: Int64

In [33]:
# Check count of values in a numeric column
dfRaw.IncomeLevel.count()

np.int64(53503)

In [34]:
# Check sum of values in a numeric column
dfRaw.IncomeLevel.sum()

np.int64(4428353656)

In [35]:
# Check max value in a numeric column
dfRaw.IncomeLevel.max()

149999

In [36]:
# Check min value in a numeric column
dfRaw.IncomeLevel.min()

20001

In [37]:
# Check mode value in a numeric column
dfRaw.IncomeLevel.mode()

0    20001
Name: IncomeLevel, dtype: int64

In [38]:
# Check mean value in a numeric column
dfRaw.IncomeLevel.mean()

np.float64(82768.32431826253)

In [39]:
# Check median value in a numeric column
dfRaw.IncomeLevel.median()

80719.0

In [40]:
# Check standard deviation value in a numeric column
dfRaw.IncomeLevel.std()

36651.07567019094

In [41]:
# Check variance value in a numeric column
dfRaw.IncomeLevel.var()

1343301347.7820625

In [43]:
x = dfRaw.Age.corr(dfRaw.CoverageAmount)
x

np.float64(0.006745728709620007)

In [44]:
dfRaw.head()

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,CCChannel,PolicyOwned,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,Chat,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2

In [45]:
# Adding a new column: using a formula (10% raise)
# Note:dfRaw['NewIncomeLevel'] is the new column. You give it the name that suits you
dfRaw['NewIncomeLevel'] = dfRaw['IncomeLevel'] * 1.1
dfRaw.head()

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,PolicyOwned,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,...,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,...,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,...,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,...,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,...,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4

In [46]:
# Adding a new column: using a function
def getAgeGroup(age:int) -> str:
  if age < 20:
    return 'Under 20'
  elif age >= 20 and age < 30:
    return '20s'
  elif age >= 30 and age < 40:
    return '30s'
  elif age >= 40 and age < 50:
    return '40s'
  elif age >= 50 and age < 60:
    return '50s'
  elif age >= 60 and age < 70:
    return '60s'
  elif age >= 70 and age < 80:
    return '70s'
  elif age >= 80 and age < 90:
    return '80s'
  elif age >= 90 and age < 100:
    return '90s'
  else:
    return 'Over 100'

In [47]:
# The above function is applied to Age column to produce a new column called 'AgeGroup' which is automatically added to the dfRaw
dfRaw['AgeGroup'] = dfRaw['Age'].apply(getAgeGroup)
dfRaw.head()

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,...,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1,20s
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,...,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,...,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,...,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1,20s
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,...,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s

In [48]:
# Showing rows with the top n largest value
n = 10
dfRaw.nlargest(n, 'CoverageAmount')

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
966,55575,40,Male,Married,Doctorate,Arunachal Pradesh,Nurse,84231,policy2,05-11-2023,...,1000000,4609,Group,Phone,In-Person Meeting,Anytime,English,Segment2,92654.1,40s
2352,83658,47,Male,Divorced,High School Diploma,Maharashtra,Salesperson,84166,policy2,12-11-2018,...,1000000,2010,Family,Email,In-Person Meeting,Anytime,French,Segment4,92582.6,40s
2650,15469,31,Male,Married,High School Diploma,Himachal Pradesh,Entrepreneur,69712,policy3,10/28/2022,...,1000000,2991,Family,Mail,Email,Morning,German,Segment2,76683.2,30s
7993,73997,33,Female,Divorced,Associate Degree,Daman and Diu,Artist,61224,policy3,8/23/2021,...,1000000,2296,Group,Email,Email,Evening,Mandarin,Segment5,67346.4,30s
12871,1598,43,Female,Widowed,Master's Degree,Uttarakhand,Artist,145090,policy3,01-10-2023,...,1000000,3348,Group,Text,Mail,Weekends,French,Segment1,159599.0,40s
15525,77369,36,Male,Widowed,Doctorate,Sikkim,Manager,138526,policy4,10-02-2018,...,1000000,3256,Group,In-Person Meeting,Mail,Afternoon,French,Segment1,152378.6,30s
17794,40622,55,Female,Widowed,High School Diploma,Kerala,Engineer,50143,policy2,1/13/2022,...,1000000,1572,Group,In-Person Meeting,In-Person Meeting,Morning,French,Segment2,55157.3,50s
18323,23797,47,Female,Married,High School Diploma,Karnataka,Salesperson,52639,policy3,6/14/2023,...,1000000,2185,Group,Mail,Text,Morning,English,Segment1,57902.9,40s
18662,55414,18,Female,Single,High School Diploma,Mizoram,Engineer,109585,policy1,10-03-2023,...,1000000,4492,Family,Phone,Text,Weekends,German,Segment1,120543.5,Under 20
18919,98084,33,Male,Divorced,High School Diploma,Punjab,Artist,36009,policy5,06-04-2019,...,1000000,1862,Business,In-Person Meeting,Mail,Evening,Mandarin,Segment4,39609.9,30s

In [49]:
# Showing rows with the least n largest value
n = 10
dfRaw.nsmallest(n, 'CoverageAmount')

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
97,22602,23,Male,Married,Associate Degree,Delhi,Lawyer,25667,policy4,1/17/2022,...,50001,2909,Business,Text,In-Person Meeting,Weekends,English,Segment4,28233.7,20s
3068,76192,63,Female,Married,Bachelor's Degree,Gujarat,Doctor,122979,policy3,09-06-2018,...,50001,4017,Group,Text,Email,Morning,Spanish,Segment2,135276.9,60s
3232,31800,57,Female,Separated,Bachelor's Degree,Assam,Teacher,126074,policy5,10/28/2018,...,50001,1061,Individual,Email,Phone,Weekends,German,Segment5,138681.4,50s
4482,54157,46,Female,Separated,Bachelor's Degree,Punjab,Nurse,109031,policy5,7/18/2019,...,50001,4467,Individual,Phone,Email,Evening,German,Segment2,119934.1,40s
5387,95073,26,Male,Widowed,Bachelor's Degree,Delhi,Entrepreneur,54207,policy3,1/27/2018,...,50001,1711,Group,Text,Text,Evening,Mandarin,Segment2,59627.7,20s
5715,67387,49,Female,Widowed,Associate Degree,Daman and Diu,Lawyer,74422,policy2,11/18/2022,...,50001,1590,Individual,In-Person Meeting,In-Person Meeting,Anytime,French,Segment2,81864.2,40s
5869,85055,55,Female,Married,Bachelor's Degree,Andaman and Nicobar Islands,Nurse,144574,policy4,2/18/2020,...,50001,1231,Family,Phone,Phone,Morning,English,Segment4,159031.4,50s
7723,82365,33,Female,Married,Master's Degree,Haryana,Lawyer,91089,policy3,02-06-2021,...,50001,824,Family,Phone,In-Person Meeting,Afternoon,German,Segment2,100197.9,30s
8196,64103,69,Female,Married,High School Diploma,Himachal Pradesh,Teacher,149247,policy4,02-04-2022,...,50001,3206,Family,Mail,Email,Anytime,Spanish,Segment4,164171.7,60s
9799,73360,22,Female,Separated,Doctorate,Daman and Diu,Entrepreneur,24118,policy5,11/14/2023,...,50001,3514,Business,Phone,Mail,Weekends,German,Segment2,26529.8,20s

In [50]:
# Searching for rows based on index
dfRaw.iloc[0]

CustomerID                          84966
Age                                    23
Gender                             Female
MaritalStatus                     Married
EducationLevel           Associate Degree
Location                          Mizoram
Occupation                   Entrepreneur
IncomeLevel                         70541
BehavioralData                    policy5
PurchaseHistory                04-10-2018
CCChannel                           Phone
PolicyOwned                       policy2
CoverageAmount                     366603
PremiumAmount                        2749
PolicyType                          Group
CustomerPreferences                 Email
PreferredChannel        In-Person Meeting
PreferredContactTime            Afternoon
PreferredLanguage                 English
SegmentationGroup                Segment5
NewIncomeLevel                    77595.1
AgeGroup                              20s
Name: 0, dtype: object

In [51]:
# Extracts the first 10 rows and ALL columns
# [rows, cols]
dfRaw.iloc[0:10,]

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,...,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1,20s
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,...,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,...,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,...,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1,20s
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,...,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s
5,60937,41,Female,Separated,Master's Degree,Uttar Pradesh,Nurse,87188,policy5,9/19/2020,...,570757,1106,Individual,Text,Text,Afternoon,English,Segment4,95906.8,40s
6,37676,55,Male,Single,Bachelor's Degree,Rajasthan,Manager,94891,policy3,07-04-2021,...,604069,3661,Group,In-Person Meeting,Text,Weekends,Mandarin,Segment5,104380.1,50s
7,54100,35,Male,Married,Master's Degree,Himachal Pradesh,Artist,61003,policy1,11-01-2021,...,418997,1148,Business,Email,Phone,Morning,English,Segment5,67103.3,30s
8,30476,43,Female,Single,Doctorate,Manipur,Salesperson,116249,policy1,9/20/2020,...,319423,2612,Business,In-Person Meeting,Text,Weekends,Mandarin,Segment2,127873.9,40s
9,39071,32,Female,Single,Master's Degree,Gujarat,Artist,49083,policy3,4/24/2020,...,701577,4595,Group,Phone,Email,Weekends,English,Segment2,53991.3,30s

In [52]:
# Extracts the first 10 rows and first 3 columns
# [rows, cols]
# Shows the 1st 10 rows and 1st 3 cols
dfRaw.iloc[0:10,0:3]

   CustomerID  Age  Gender
0       84966   23  Female
1       95568   26    Male
2       10544   29  Female
3       77033   20    Male
4       88160   25  Female
5       60937   41  Female
6       37676   55    Male
7       54100   35    Male
8       30476   43  Female
9       39071   32  Female

In [53]:
dfRaw.loc[0]

CustomerID                          84966
Age                                    23
Gender                             Female
MaritalStatus                     Married
EducationLevel           Associate Degree
Location                          Mizoram
Occupation                   Entrepreneur
IncomeLevel                         70541
BehavioralData                    policy5
PurchaseHistory                04-10-2018
CCChannel                           Phone
PolicyOwned                       policy2
CoverageAmount                     366603
PremiumAmount                        2749
PolicyType                          Group
CustomerPreferences                 Email
PreferredChannel        In-Person Meeting
PreferredContactTime            Afternoon
PreferredLanguage                 English
SegmentationGroup                Segment5
NewIncomeLevel                    77595.1
AgeGroup                              20s
Name: 0, dtype: object

In [54]:
dfRaw.loc[0:10]

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,...,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1,20s
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,...,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,...,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,...,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1,20s
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,...,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s
5,60937,41,Female,Separated,Master's Degree,Uttar Pradesh,Nurse,87188,policy5,9/19/2020,...,570757,1106,Individual,Text,Text,Afternoon,English,Segment4,95906.8,40s
6,37676,55,Male,Single,Bachelor's Degree,Rajasthan,Manager,94891,policy3,07-04-2021,...,604069,3661,Group,In-Person Meeting,Text,Weekends,Mandarin,Segment5,104380.1,50s
7,54100,35,Male,Married,Master's Degree,Himachal Pradesh,Artist,61003,policy1,11-01-2021,...,418997,1148,Business,Email,Phone,Morning,English,Segment5,67103.3,30s
8,30476,43,Female,Single,Doctorate,Manipur,Salesperson,116249,policy1,9/20/2020,...,319423,2612,Business,In-Person Meeting,Text,Weekends,Mandarin,Segment2,127873.9,40s
9,39071,32,Female,Single,Master's Degree,Gujarat,Artist,49083,policy3,4/24/2020,...,701577,4595,Group,Phone,Email,Weekends,English,Segment2,53991.3,30s
10,38477,69,Male,Widowed,Master's Degree,Andaman and Nicobar Islands,Artist,62099,policy2,3/20/2022,...,898873,2935,Business,In-Person Meeting,Text,Weekends,French,Segment3,68308.9,60s

In [55]:
dfRaw.loc[0:10][['CustomerID', 'Age', 'MaritalStatus']]

    CustomerID  Age MaritalStatus
0        84966   23       Married
1        95568   26       Widowed
2        10544   29        Single
3        77033   20      Divorced
4        88160   25     Separated
5        60937   41     Separated
6        37676   55        Single
7        54100   35       Married
8        30476   43        Single
9        39071   32        Single
10       38477   69       Widowed

In [56]:
dfRaw.set_index('CustomerID',inplace=True)

In [57]:
dfRaw.sample(3)

,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,CCChannel,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
CustomerID,,,,,,,,,,,,,,,,,,,,,
12880,55,Female,Divorced,Master's Degree,Assam,Manager,119152,policy3,6/23/2021,Mobile App,...,279790,1128,Group,Mail,Mail,Evening,Spanish,Segment3,131067.2,50s
93089,31,Male,Married,Associate Degree,Uttar Pradesh,Nurse,56026,policy3,12-11-2018,Phone,...,189216,3197,Group,In-Person Meeting,Mail,Evening,German,Segment1,61628.6,30s
8702,64,Female,Divorced,Doctorate,Nagaland,Manager,114693,policy4,8/27/2020,Mobile App,...,629260,4927,Business,Email,Phone,Afternoon,German,Segment5,126162.3,60s

In [58]:
dfRaw.loc[1444]

Age                                  46
Gender                             Male
MaritalStatus                    Single
EducationLevel          Master's Degree
Location                      Jharkhand
Occupation                      Manager
IncomeLevel                      131375
BehavioralData                  policy5
PurchaseHistory               8/16/2018
CCChannel                          Chat
PolicyOwned                     policy2
CoverageAmount                   754277
PremiumAmount                      2262
PolicyType                        Group
CustomerPreferences               Email
PreferredChannel                  Phone
PreferredContactTime           Weekends
PreferredLanguage                French
SegmentationGroup              Segment1
NewIncomeLevel                 144512.5
AgeGroup                            40s
Name: 1444, dtype: object

In [59]:
ids = [10544, 38477, 88160]
dfRaw.loc[ids]

,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,CCChannel,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
CustomerID,,,,,,,,,,,,,,,,,,,,,
10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,...,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s
10544,32,Female,Separated,Doctorate,Delhi,Entrepreneur,53427,policy2,7/18/2022,Email,...,570742,1876,Individual,In-Person Meeting,In-Person Meeting,Anytime,German,Segment3,58769.7,30s
38477,69,Male,Widowed,Master's Degree,Andaman and Nicobar Islands,Artist,62099,policy2,3/20/2022,In-Person,...,898873,2935,Business,In-Person Meeting,Text,Weekends,French,Segment3,68308.9,60s
38477,30,Female,Married,Doctorate,Goa,Teacher,122634,policy4,9/17/2020,In-Person,...,88294,1489,Business,Email,Phone,Morning,French,Segment3,134897.4,30s
88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,...,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s
88160,70,Female,Divorced,Doctorate,Himachal Pradesh,Entrepreneur,82284,policy3,2/21/2023,Phone,...,395878,4602,Family,In-Person Meeting,Email,Morning,German,Segment4,90512.4,70s
88160,24,Female,Married,Associate Degree,Dadra and Nagar Haveli,Nurse,143216,policy3,3/23/2020,Chat,...,968651,3507,Group,Phone,Text,Evening,German,Segment4,157537.6,20s
88160,38,Male,Married,High School Diploma,Delhi,Artist,82212,policy5,7/13/2019,Phone,...,613780,747,Group,Mail,Email,Evening,Mandarin,Segment4,90433.2,30s

In [60]:
dfRaw.filter(items=['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'Location', 'NewIncomeLevel'], axis=1)

,Age,AgeGroup,Gender,MaritalStatus,Location,NewIncomeLevel
CustomerID,,,,,,
84966,23,20s,Female,Married,Mizoram,77595.1
95568,26,20s,Male,Widowed,Goa,59584.8
10544,29,20s,Female,Single,Rajasthan,81288.9
77033,20,20s,Male,Divorced,Sikkim,69719.1
88160,25,20s,Female,Separated,West Bengal,42673.4
...,...,...,...,...,...,...
44809,35,30s,Female,Divorced,Andaman and Nicobar Islands,132935.0
65485,61,60s,Male,Single,Himachal Pradesh,134539.9
26213,25,20s,Male,Divorced,Assam,54183.8
63136,42,40s,Male,Married,Andhra Pradesh,72931.1
62125,20,20s,Male,Divorced,Daman and Diu,150295.2

In [61]:
dfRaw.reset_index(inplace=True)

In [62]:
dfRaw.head()

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,...,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1,20s
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,...,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,...,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,...,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1,20s
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,...,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s

In [63]:
# Capitalise the first letter of BehavioralData column
dfRaw['BehavioralData'] = dfRaw['BehavioralData'].str.capitalize()
dfRaw.head()

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,Policy5,04-10-2018,...,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1,20s
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,Policy5,11-06-2018,...,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,Policy5,06-05-2021,...,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,Policy5,09-02-2018,...,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1,20s
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,Policy1,09-10-2018,...,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s

In [64]:
# Insert hypen before the last character in behavioraldata column e.g. Policy5 becomes Policy-5
dfRaw['BehavioralData'] = dfRaw['BehavioralData'].str[:-1] + '-' + dfRaw['BehavioralData'].str[-1:]
dfRaw.head()

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,Policy-5,04-10-2018,...,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1,20s
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,Policy-5,11-06-2018,...,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,Policy-5,06-05-2021,...,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,Policy-5,09-02-2018,...,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1,20s
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,Policy-1,09-10-2018,...,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s

In [65]:
# Get a list of even numbers less than 20
evenNumbers = [x for x in range(20) if x % 2 == 0]

dfRaw.filter(items=evenNumbers, axis=0)

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,Policy-5,04-10-2018,...,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1,20s
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,Policy-5,06-05-2021,...,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,Policy-1,09-10-2018,...,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s
6,37676,55,Male,Single,Bachelor's Degree,Rajasthan,Manager,94891,Policy-3,07-04-2021,...,604069,3661,Group,In-Person Meeting,Text,Weekends,Mandarin,Segment5,104380.1,50s
8,30476,43,Female,Single,Doctorate,Manipur,Salesperson,116249,Policy-1,9/20/2020,...,319423,2612,Business,In-Person Meeting,Text,Weekends,Mandarin,Segment2,127873.9,40s
10,38477,69,Male,Widowed,Master's Degree,Andaman and Nicobar Islands,Artist,62099,Policy-2,3/20/2022,...,898873,2935,Business,In-Person Meeting,Text,Weekends,French,Segment3,68308.9,60s
12,6580,31,Female,Single,Associate Degree,Tripura,Teacher,90301,Policy-5,10/28/2018,...,299600,2861,Group,In-Person Meeting,Mail,Evening,French,Segment1,99331.1,30s
14,34814,64,Male,Single,High School Diploma,Nagaland,Doctor,105009,Policy-3,09-05-2020,...,399139,2760,Individual,In-Person Meeting,Email,Evening,German,Segment3,115509.9,60s
16,24881,69,Female,Married,Bachelor's Degree,Karnataka,Artist,114236,Policy-3,11/16/2018,...,667081,4634,Group,Mail,Mail,Weekends,Spanish,Segment1,125659.6,60s
18,38654,53,Male,Divorced,Associate Degree,Odisha,Manager,49224,Policy-5,10/26/2020,...,869812,4342,Group,Mail,Mail,Evening,Mandarin,Segment1,54146.4,50s

In [66]:
# Get a list of odd numbers less than 20
oddNumbers = [x for x in range(20) if x % 2 != 0]

dfRaw.filter(items=oddNumbers, axis=0)

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,Policy-5,11-06-2018,...,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,Policy-5,09-02-2018,...,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1,20s
5,60937,41,Female,Separated,Master's Degree,Uttar Pradesh,Nurse,87188,Policy-5,9/19/2020,...,570757,1106,Individual,Text,Text,Afternoon,English,Segment4,95906.8,40s
7,54100,35,Male,Married,Master's Degree,Himachal Pradesh,Artist,61003,Policy-1,11-01-2021,...,418997,1148,Business,Email,Phone,Morning,English,Segment5,67103.3,30s
9,39071,32,Female,Single,Master's Degree,Gujarat,Artist,49083,Policy-3,4/24/2020,...,701577,4595,Group,Phone,Email,Weekends,English,Segment2,53991.3,30s
11,38329,47,Female,Married,Associate Degree,Uttar Pradesh,Lawyer,110698,Policy-4,05-10-2021,...,777280,4517,Business,In-Person Meeting,Text,Afternoon,German,Segment2,121767.8,40s
13,67128,65,Female,Widowed,High School Diploma,Himachal Pradesh,Entrepreneur,24648,Policy-3,12/28/2018,...,276109,3971,Individual,In-Person Meeting,In-Person Meeting,Evening,English,Segment1,27112.8,60s
15,86048,53,Male,Single,Bachelor's Degree,Manipur,Engineer,29783,Policy-1,08-06-2021,...,807659,2334,Group,In-Person Meeting,Email,Afternoon,Spanish,Segment5,32761.3,50s
17,24076,48,Female,Divorced,Bachelor's Degree,Andaman and Nicobar Islands,Teacher,107359,Policy-2,10/15/2023,...,963585,2802,Business,Text,In-Person Meeting,Evening,Mandarin,Segment2,118094.9,40s
19,47840,62,Male,Divorced,Associate Degree,Tripura,Entrepreneur,117264,Policy-4,07-11-2019,...,777902,1843,Group,Text,Mail,Weekends,English,Segment4,128990.4,60s

In [67]:
# Replace entries in EducationLevel based on the following conditions:
# Doctorate:PhD, Associate Qualification:HND, Bachelor's Qualification:BSc,High School Diploma:SSCE
dfRaw['EducationLevel'] = dfRaw['EducationLevel'].str.replace('Doctorate', 'Doctorate Degree')
dfRaw

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,CoverageAmount,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,Policy-5,04-10-2018,...,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1,20s
1,95568,26,Male,Widowed,Doctorate Degree,Goa,Manager,54168,Policy-5,11-06-2018,...,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,Policy-5,06-05-2021,...,773926,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,Policy-5,09-02-2018,...,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1,20s
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,Policy-1,09-10-2018,...,366506,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53498,44809,35,Female,Divorced,Associate Degree,Andaman and Nicobar Islands,Salesperson,120850,Policy-3,01-01-2019,...,586401,4404,Family,In-Person Meeting,Phone,Afternoon,German,Segment5,132935.0,30s
53499,65485,61,Male,Single,Doctorate Degree,Himachal Pradesh,Entrepreneur,122309,Policy-5,5/18/2021,...,637733,1285,Group,Text,Mail,Afternoon,German,Segment1,134539.9,60s
53500,26213,25,Male,Divorced,Doctorate Degree,Assam,Teacher,49258,Policy-2,11/27/2018,...,631057,4407,Individual,Text,Text,Weekends,French,Segment4,54183.8,20s
53501,63136,42,Male,Married,Doctorate Degree,Andhra Pradesh,Artist,66301,Policy-4,06-04-2021,...,730385,4482,Business,Mail,Phone,Morning,French,Segment5,72931.1,40s
53502,62125,20,Male,Divorced,Doctorate Degree,Daman and Diu,Salesperson,136632,Policy-2,10/14/2022,...,743262,4499,Group,Text,In-Person Meeting,Evening,German,Segment2,150295.2,20s

In [68]:
# Replace entries in EducationLevel using lambda function based on the following conditions:
# Doctorate:PhD, Associate Qualification:HND, Bachelor's Qualification:BSc,High School Diploma:SSCE
dfRaw['Qualification'] = dfRaw['EducationLevel'].apply(
    lambda x: 'PhD' if x == 'Doctorate Degree' else \
              ('HND' if x == 'Associate Degree' else \
               ('BSc' if x == "Bachelor's Degree" else \
                ('SSCE' if x == 'High School Diploma' else x)))
)
dfRaw

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup,Qualification
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,Policy-5,04-10-2018,...,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,77595.1,20s,HND
1,95568,26,Male,Widowed,Doctorate Degree,Goa,Manager,54168,Policy-5,11-06-2018,...,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s,PhD
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,Policy-5,06-05-2021,...,4413,Group,Email,Mail,Evening,German,Segment3,81288.9,20s,HND
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,Policy-5,09-02-2018,...,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,69719.1,20s,BSc
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,Policy-1,09-10-2018,...,1276,Family,Email,Text,Weekends,English,Segment2,42673.4,20s,BSc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53498,44809,35,Female,Divorced,Associate Degree,Andaman and Nicobar Islands,Salesperson,120850,Policy-3,01-01-2019,...,4404,Family,In-Person Meeting,Phone,Afternoon,German,Segment5,132935.0,30s,HND
53499,65485,61,Male,Single,Doctorate Degree,Himachal Pradesh,Entrepreneur,122309,Policy-5,5/18/2021,...,1285,Group,Text,Mail,Afternoon,German,Segment1,134539.9,60s,PhD
53500,26213,25,Male,Divorced,Doctorate Degree,Assam,Teacher,49258,Policy-2,11/27/2018,...,4407,Individual,Text,Text,Weekends,French,Segment4,54183.8,20s,PhD
53501,63136,42,Male,Married,Doctorate Degree,Andhra Pradesh,Artist,66301,Policy-4,06-04-2021,...,4482,Business,Mail,Phone,Morning,French,Segment5,72931.1,40s,PhD
53502,62125,20,Male,Divorced,Doctorate Degree,Daman and Diu,Salesperson,136632,Policy-2,10/14/2022,...,4499,Group,Text,In-Person Meeting,Evening,German,Segment2,150295.2,20s,PhD

In [69]:
# Filter using items parameter.
desiredColumns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel']
dfRaw.filter(items= desiredColumns, axis=1)

       CustomerID  Age AgeGroup  Gender MaritalStatus     EducationLevel
0           84966   23      20s  Female       Married   Associate Degree
1           95568   26      20s    Male       Widowed   Doctorate Degree
2           10544   29      20s  Female        Single   Associate Degree
3           77033   20      20s    Male      Divorced  Bachelor's Degree
4           88160   25      20s  Female     Separated  Bachelor's Degree
...           ...  ...      ...     ...           ...                ...
53498       44809   35      30s  Female      Divorced   Associate Degree
53499       65485   61      60s    Male        Single   Doctorate Degree
53500       26213   25      20s    Male      Divorced   Doctorate Degree
53501       63136   42      40s    Male       Married   Doctorate Degree
53502       62125   20      20s    Male      Divorced   Doctorate Degree

[53503 rows x 6 columns]

In [70]:
# Filter dfRaw
# Shows rows that contain 'Level' as part of their column name
dfRaw.filter(like='Level', axis=1)

          EducationLevel  IncomeLevel  NewIncomeLevel
0       Associate Degree        70541         77595.1
1       Doctorate Degree        54168         59584.8
2       Associate Degree        73899         81288.9
3      Bachelor's Degree        63381         69719.1
4      Bachelor's Degree        38794         42673.4
...                  ...          ...             ...
53498   Associate Degree       120850        132935.0
53499   Doctorate Degree       122309        134539.9
53500   Doctorate Degree        49258         54183.8
53501   Doctorate Degree        66301         72931.1
53502   Doctorate Degree       136632        150295.2

[53503 rows x 3 columns]

In [71]:
# This shows ALL columns
dfRaw.query('`CustomerID` == 30476')

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup,Qualification
8,30476,43,Female,Single,Doctorate Degree,Manipur,Salesperson,116249,Policy-1,9/20/2020,...,2612,Business,In-Person Meeting,Text,Weekends,Mandarin,Segment2,127873.9,40s,PhD
32267,30476,55,Female,Widowed,High School Diploma,Nagaland,Nurse,38385,Policy-2,6/18/2022,...,1744,Group,Mail,Mail,Weekends,French,Segment4,42223.5,50s,SSCE

In [72]:
# This shows specific columns
dfRaw.query('`CustomerID` == 30476')[['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
8,30476,43,40s,Female,Single,Doctorate Degree,127873.9,Business,319423,PhD
32267,30476,55,50s,Female,Widowed,High School Diploma,42223.5,Group,500668,SSCE

In [73]:
# This shows specific columns
columns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']
dfRaw.query('`CustomerID` == 30476')[columns]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
8,30476,43,40s,Female,Single,Doctorate Degree,127873.9,Business,319423,PhD
32267,30476,55,50s,Female,Widowed,High School Diploma,42223.5,Group,500668,SSCE

In [74]:
x = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']
dfRaw.query("Age == 44")[x]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
81,65220,44,40s,Female,Married,High School Diploma,128123.6,Group,758402,SSCE
82,34756,44,40s,Female,Married,Associate Degree,36172.4,Individual,257434,HND
120,44973,44,40s,Male,Divorced,Associate Degree,58105.3,Group,875673,HND
190,7555,44,40s,Male,Separated,High School Diploma,63196.1,Business,565867,SSCE
498,59231,44,40s,Male,Married,High School Diploma,163986.9,Group,203000,SSCE
...,...,...,...,...,...,...,...,...,...,...
53203,70863,44,40s,Female,Divorced,Bachelor's Degree,55165.0,Business,775727,BSc
53253,89438,44,40s,Female,Single,Bachelor's Degree,100310.1,Group,177880,BSc
53383,74195,44,40s,Male,Separated,High School Diploma,134062.5,Business,792044,SSCE
53407,96445,44,40s,Female,Married,Associate Degree,130444.6,Family,494882,HND
53417,78222,44,40s,Male,Married,High School Diploma,128294.1,Family,396951,SSCE

In [75]:
# Retrieves rows of policy holders between age 20 and 30
columns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']
dfRaw.query('Age >= 20 and Age <= 30')[columns]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
0,84966,23,20s,Female,Married,Associate Degree,77595.1,Group,366603,HND
1,95568,26,20s,Male,Widowed,Doctorate Degree,59584.8,Group,780236,PhD
2,10544,29,20s,Female,Single,Associate Degree,81288.9,Group,773926,HND
3,77033,20,20s,Male,Divorced,Bachelor's Degree,69719.1,Family,787815,BSc
4,88160,25,20s,Female,Separated,Bachelor's Degree,42673.4,Family,366506,BSc
...,...,...,...,...,...,...,...,...,...,...
53478,39996,22,20s,Male,Separated,Doctorate Degree,83512.0,Group,168270,PhD
53482,73236,26,20s,Male,Divorced,Master's Degree,78114.3,Group,403936,Master's Degree
53497,44828,24,20s,Female,Married,Master's Degree,133686.3,Group,506115,Master's Degree
53500,26213,25,20s,Male,Divorced,Doctorate Degree,54183.8,Individual,631057,PhD
53502,62125,20,20s,Male,Divorced,Doctorate Degree,150295.2,Group,743262,PhD

In [76]:
# Retrieves rows of male policy holders who are below 20 wit coverage amount over 280k
columns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']
dfRaw.query("Gender == 'Male' and Age < 20 and CoverageAmount > 280000")[columns]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
214,96542,19,Under 20,Male,Widowed,Master's Degree,149109.4,Business,422449,Master's Degree
382,2944,18,Under 20,Male,Separated,High School Diploma,159359.2,Family,925458,SSCE
576,5180,19,Under 20,Male,Married,Master's Degree,48954.4,Family,795079,Master's Degree
911,88321,19,Under 20,Male,Divorced,Bachelor's Degree,74174.1,Family,395783,BSc
920,75171,19,Under 20,Male,Single,Bachelor's Degree,80584.9,Group,783560,BSc
...,...,...,...,...,...,...,...,...,...,...
53317,40864,19,Under 20,Male,Widowed,High School Diploma,27800.3,Group,650287,SSCE
53349,91801,19,Under 20,Male,Separated,Associate Degree,27882.8,Business,762656,HND
53364,6716,19,Under 20,Male,Separated,Doctorate Degree,55389.4,Group,387677,PhD
53438,46850,19,Under 20,Male,Married,Associate Degree,125700.3,Family,665048,HND
53450,40187,19,Under 20,Male,Married,Doctorate Degree,31152.0,Group,862219,PhD

In [78]:
# Retrieve records of policy holders meeting multiple conditions
columns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']
dfRaw.query("Gender == 'Male' and Age < 20 and EducationLevel == 'Doctorate Degree' and CoverageAmount > 280000 and CoverageAmount < 450000")[columns]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
1763,86571,19,Under 20,Male,Married,Doctorate Degree,88684.2,Business,402258,PhD
7172,49134,19,Under 20,Male,Separated,Doctorate Degree,46536.6,Group,390880,PhD
7537,28266,19,Under 20,Male,Separated,Doctorate Degree,67489.4,Group,312150,PhD
8420,67580,19,Under 20,Male,Single,Doctorate Degree,76682.1,Family,316789,PhD
8618,26761,19,Under 20,Male,Single,Doctorate Degree,123601.5,Family,427779,PhD
8952,71700,18,Under 20,Male,Widowed,Doctorate Degree,43601.8,Family,388589,PhD
11572,16001,19,Under 20,Male,Widowed,Doctorate Degree,134461.8,Group,388187,PhD
12940,46606,19,Under 20,Male,Divorced,Doctorate Degree,136226.2,Business,405349,PhD
14156,76084,19,Under 20,Male,Married,Doctorate Degree,47757.6,Business,296145,PhD
16066,61350,18,Under 20,Male,Separated,Doctorate Degree,122790.8,Business,417424,PhD
17221,64086,18,Under 20,Male,Single,Doctorate Degree,44234.3,Business,408797,PhD
18279,46920,19,Under 20,Male,Single,Doctorate Degree,101987.6,Individual,379423,PhD
19514,66559,18,Under 20,Male,Single,Doctorate Degree,154144.1,Business,405717,PhD
20172,2285,18,Under 20,Male,Married,Doctorate Degree,109904.3,Individual,281146,PhD
20622,61113,19,Under 20,Male,Divorced,Doctorate Degree,70371.4,Family,313813,PhD
22819,22050,19,Under 20,Male,Separated,Doctorate Degree,129038.8,Group,324746,PhD
23286,64371,19,Under 20,Male,Divorced,Doctorate Degree,119413.8,Group,288652,PhD
30153,49610,19,Under 20,Male,Single,Doctorate Degree,103657.4,Family,308399,PhD
31477,55357,19,Under 20,Male,Divorced,Doctorate Degree,76583.1,Family,388833,PhD
35589,30614,19,Under 20,Male,Divorced,Doctorate Degree,66526.9,Family,298145,PhD
36591,5520,19,Under 20,Male,Divorced,Doctorate Degree,86266.4,Family,394845,PhD
40262,45252,19,Under 20,Male,Married,Doctorate Degree,121423.5,Family,313960,PhD
53364,6716,19,Under 20,Male,Separated,Doctorate Degree,55389.4,Group,387677,PhD

In [79]:
# Retrieve rows of policy holders in their 20s or 30s or 40s
x = ['20s', '30s', '40s']
columns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']
dfRaw.query('AgeGroup in @x')[columns]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
0,84966,23,20s,Female,Married,Associate Degree,77595.1,Group,366603,HND
1,95568,26,20s,Male,Widowed,Doctorate Degree,59584.8,Group,780236,PhD
2,10544,29,20s,Female,Single,Associate Degree,81288.9,Group,773926,HND
3,77033,20,20s,Male,Divorced,Bachelor's Degree,69719.1,Family,787815,BSc
4,88160,25,20s,Female,Separated,Bachelor's Degree,42673.4,Family,366506,BSc
...,...,...,...,...,...,...,...,...,...,...
53497,44828,24,20s,Female,Married,Master's Degree,133686.3,Group,506115,Master's Degree
53498,44809,35,30s,Female,Divorced,Associate Degree,132935.0,Family,586401,HND
53500,26213,25,20s,Male,Divorced,Doctorate Degree,54183.8,Individual,631057,PhD
53501,63136,42,40s,Male,Married,Doctorate Degree,72931.1,Business,730385,PhD
53502,62125,20,20s,Male,Divorced,Doctorate Degree,150295.2,Group,743262,PhD

In [80]:
# Retrieve rows of policy holders in their 40s or 50s or 60s
x = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']
dfRaw.query("AgeGroup == '40s' or AgeGroup == '50s' or AgeGroup == '60s'")[x]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
5,60937,41,40s,Female,Separated,Master's Degree,95906.8,Individual,570757,Master's Degree
6,37676,55,50s,Male,Single,Bachelor's Degree,104380.1,Group,604069,BSc
8,30476,43,40s,Female,Single,Doctorate Degree,127873.9,Business,319423,PhD
10,38477,69,60s,Male,Widowed,Master's Degree,68308.9,Business,898873,Master's Degree
11,38329,47,40s,Female,Married,Associate Degree,121767.8,Business,777280,HND
...,...,...,...,...,...,...,...,...,...,...
53491,77385,40,40s,Female,Separated,High School Diploma,38646.3,Family,146309,SSCE
53493,35647,48,40s,Male,Widowed,Bachelor's Degree,67637.9,Individual,939559,BSc
53494,78975,45,40s,Male,Separated,High School Diploma,75696.5,Group,702025,SSCE
53499,65485,61,60s,Male,Single,Doctorate Degree,134539.9,Group,637733,PhD
53501,63136,42,40s,Male,Married,Doctorate Degree,72931.1,Business,730385,PhD

In [84]:
# Shows rows that contain 'Doctorate' as part of their row values
dfRaw[dfRaw['EducationLevel'].str.contains('Doctorate')]

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,PremiumAmount,PolicyType,CustomerPreferences,PreferredChannel,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup,Qualification
1,95568,26,Male,Widowed,Doctorate Degree,Goa,Manager,54168,Policy-5,11-06-2018,...,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,59584.8,20s,PhD
8,30476,43,Female,Single,Doctorate Degree,Manipur,Salesperson,116249,Policy-1,9/20/2020,...,2612,Business,In-Person Meeting,Text,Weekends,Mandarin,Segment2,127873.9,40s,PhD
25,62346,64,Female,Single,Doctorate Degree,Delhi,Entrepreneur,107930,Policy-3,12/14/2021,...,4137,Individual,Email,Mail,Morning,Spanish,Segment5,118723.0,60s,PhD
28,88530,63,Male,Single,Doctorate Degree,Gujarat,Doctor,117967,Policy-1,7/26/2023,...,1821,Business,Phone,Text,Weekends,Mandarin,Segment5,129763.7,60s,PhD
31,82780,51,Female,Single,Doctorate Degree,Goa,Engineer,107642,Policy-1,12-08-2022,...,4482,Family,Phone,Text,Morning,German,Segment2,118406.2,50s,PhD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53496,64861,31,Female,Widowed,Doctorate Degree,Andaman and Nicobar Islands,Salesperson,102026,Policy-2,4/28/2019,...,4487,Group,Email,Phone,Weekends,German,Segment4,112228.6,30s,PhD
53499,65485,61,Male,Single,Doctorate Degree,Himachal Pradesh,Entrepreneur,122309,Policy-5,5/18/2021,...,1285,Group,Text,Mail,Afternoon,German,Segment1,134539.9,60s,PhD
53500,26213,25,Male,Divorced,Doctorate Degree,Assam,Teacher,49258,Policy-2,11/27/2018,...,4407,Individual,Text,Text,Weekends,French,Segment4,54183.8,20s,PhD
53501,63136,42,Male,Married,Doctorate Degree,Andhra Pradesh,Artist,66301,Policy-4,06-04-2021,...,4482,Business,Mail,Phone,Morning,French,Segment5,72931.1,40s,PhD
53502,62125,20,Male,Divorced,Doctorate Degree,Daman and Diu,Salesperson,136632,Policy-2,10/14/2022,...,4499,Group,Text,In-Person Meeting,Evening,German,Segment2,150295.2,20s,PhD

In [85]:
# Retrieve records of policy holders who hold any of SSCE, HND or BSc
xFilter = ['SSCE', 'HND', 'BSc']
xColumns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']

dfRaw[dfRaw["Qualification"].isin(xFilter)][xColumns]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
0,84966,23,20s,Female,Married,Associate Degree,77595.1,Group,366603,HND
2,10544,29,20s,Female,Single,Associate Degree,81288.9,Group,773926,HND
3,77033,20,20s,Male,Divorced,Bachelor's Degree,69719.1,Family,787815,BSc
4,88160,25,20s,Female,Separated,Bachelor's Degree,42673.4,Family,366506,BSc
6,37676,55,50s,Male,Single,Bachelor's Degree,104380.1,Group,604069,BSc
...,...,...,...,...,...,...,...,...,...,...
53492,68215,37,30s,Female,Divorced,Bachelor's Degree,110927.3,Group,904201,BSc
53493,35647,48,40s,Male,Widowed,Bachelor's Degree,67637.9,Individual,939559,BSc
53494,78975,45,40s,Male,Separated,High School Diploma,75696.5,Group,702025,SSCE
53495,60247,31,30s,Male,Widowed,Associate Degree,138556.0,Group,694018,HND
53498,44809,35,30s,Female,Divorced,Associate Degree,132935.0,Family,586401,HND

In [86]:
# Retrieve records of policy holders who are 21 years old
xFilter = dfRaw["Age"] == 21
xColumns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']
dfRaw[xFilter][xColumns]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
113,89406,21,20s,Male,Married,Bachelor's Degree,91877.5,Group,586222,BSc
169,91959,21,20s,Male,Married,High School Diploma,141619.5,Family,594296,SSCE
374,15041,21,20s,Male,Widowed,Bachelor's Degree,106675.8,Individual,555785,BSc
502,4254,21,20s,Male,Separated,Master's Degree,80656.4,Group,992311,Master's Degree
704,32638,21,20s,Female,Single,Doctorate Degree,150635.1,Business,202557,PhD
...,...,...,...,...,...,...,...,...,...,...
53093,69854,21,20s,Male,Single,High School Diploma,97683.3,Family,437943,SSCE
53112,3501,21,20s,Female,Married,Master's Degree,54327.9,Business,951888,Master's Degree
53124,1907,21,20s,Female,Separated,Bachelor's Degree,56911.8,Group,188959,BSc
53264,87570,21,20s,Male,Widowed,Master's Degree,24546.5,Group,87602,Master's Degree
53440,65968,21,20s,Male,Widowed,Associate Degree,94661.6,Individual,170521,HND

In [87]:
# Retrieve records of policy holders who are 20 years old and hold just SSCE
xFilter = (dfRaw["Age"] == 20) & (dfRaw["Qualification"] == 'SSCE')
xColumns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification']
dfRaw[xFilter][xColumns]

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification
131,1059,20,20s,Female,Separated,High School Diploma,38161.2,Family,214966,SSCE
160,36158,20,20s,Male,Widowed,High School Diploma,90039.4,Business,849413,SSCE
546,58986,20,20s,Female,Widowed,High School Diploma,52200.5,Business,166261,SSCE
595,33290,20,20s,Female,Married,High School Diploma,35083.4,Business,576116,SSCE
596,72780,20,20s,Female,Single,High School Diploma,56564.2,Family,796174,SSCE
...,...,...,...,...,...,...,...,...,...,...
52283,30130,20,20s,Female,Single,High School Diploma,29938.7,Individual,174501,SSCE
52415,32732,20,20s,Male,Married,High School Diploma,133652.2,Individual,409318,SSCE
52800,31970,20,20s,Female,Separated,High School Diploma,113616.8,Group,184384,SSCE
52927,72918,20,20s,Male,Widowed,High School Diploma,146449.6,Family,627597,SSCE
52949,70739,20,20s,Male,Single,High School Diploma,58273.6,Group,604678,SSCE

In [88]:
# Aggregating data using GroupBy
# Example 1: Groupby one dimension, one measure
result = dfRaw.groupby('Gender')['CoverageAmount'].sum()
result

Gender
Female    12793053230
Male      13561496758
Name: CoverageAmount, dtype: int64

In [89]:
# Example 2: Groupby one dimension, one measure
result = dfRaw.groupby('MaritalStatus')['CoverageAmount'].sum()
result

MaritalStatus
Divorced     6500521162
Married      6618275754
Separated    4308576259
Single       4498963532
Widowed      4428213281
Name: CoverageAmount, dtype: int64

In [90]:
# Example 3: Groupby multiple dimensions, one measure
result = dfRaw.groupby(['MaritalStatus', 'Gender'])['CoverageAmount'].sum()
result

MaritalStatus  Gender
Divorced       Female    3201015869
               Male      3299505293
Married        Female    3281145593
               Male      3337130161
Separated      Female    2143525173
               Male      2165051086
Single         Female    2162206374
               Male      2336757158
Widowed        Female    2005160221
               Male      2423053060
Name: CoverageAmount, dtype: int64

In [91]:
result = dfRaw.groupby(['Gender', 'MaritalStatus'])['CoverageAmount'].sum()
result

Gender  MaritalStatus
Female  Divorced         3201015869
        Married          3281145593
        Separated        2143525173
        Single           2162206374
        Widowed          2005160221
Male    Divorced         3299505293
        Married          3337130161
        Separated        2165051086
        Single           2336757158
        Widowed          2423053060
Name: CoverageAmount, dtype: int64

In [92]:
# Example 4: Groupby multiple dimensions, one measure
dimensions = ['MaritalStatus', 'Gender']
measures = ['CoverageAmount']

result = dfRaw.groupby(dimensions)[measures].sum()
result

                      CoverageAmount
MaritalStatus Gender
Divorced      Female      3201015869
              Male        3299505293
Married       Female      3281145593
              Male        3337130161
Separated     Female      2143525173
              Male        2165051086
Single        Female      2162206374
              Male        2336757158
Widowed       Female      2005160221
              Male        2423053060

In [93]:
# Example 5: Groupby multiple dimensions, multiple measures
dimensions = ['MaritalStatus', 'Gender']
measures = ['CoverageAmount', 'PremiumAmount']

result = dfRaw.groupby(dimensions)[measures].sum()
result

                      CoverageAmount  PremiumAmount
MaritalStatus Gender
Divorced      Female      3201015869       19990108
              Male        3299505293       19711639
Married       Female      3281145593       20257324
              Male        3337130161       20364610
Separated     Female      2143525173       13656046
              Male        2165051086       13484677
Single        Female      2162206374       13032370
              Male        2336757158       13920423
Widowed       Female      2005160221       12726272
              Male        2423053060       14633683

In [95]:
# Example 6: Groupby multiple dimensions, one measure and many aggregate functions
dimensions = ['MaritalStatus', 'Gender']
measures = ['CoverageAmount']

result = dfRaw.groupby(dimensions)[measures].agg(['sum', 'mean', 'count', 'max', 'min', 'std'])
result

                     CoverageAmount                                       \
                                sum           mean count      max    min
MaritalStatus Gender
Divorced      Female     3201015869  490953.354141  6520  1000000  50001
              Male       3299505293  497587.889157  6631  1000000  50001
Married       Female     3281145593  499717.574322  6566  1000000  50001
              Male       3337130161  501597.799639  6653  1000000  50001
Separated     Female     2143525173  487054.117928  4401  1000000  50001
              Male       2165051086  485437.463229  4460  1000000  50001
Single        Female     2162206374  492417.757686  4391  1000000  50001
              Male       2336757158  486419.058701  4804   997385  50001
Widowed       Female     2005160221  485981.633786  4126  1000000  50001
              Male       2423053060  489406.798627  4951  1000000  50001


                                std
MaritalStatus Gender
Divorced      Female  270997.035956
              Male    274613.070636
Married       Female  270378.912243
              Male    271371.237427
Separated     Female  266077.144602
              Male    268931.946673
Single        Female  265224.488426
              Male    265393.099274
Widowed       Female  261400.745539
              Male    262478.024095

In [96]:
# Example 6: Groupby multiple dimensions, one measure and many aggregate functions + row filter(s)
dimensions = ['MaritalStatus', 'Gender']
measures = ['CoverageAmount']

# Apply the age filter before grouping and aggregating
filtered_df = dfRaw[dfRaw['Age'] >= 25]
result = filtered_df.groupby(dimensions)[measures].agg(['sum', 'mean', 'count'])
result

                     CoverageAmount
                                sum           mean count
MaritalStatus Gender
Divorced      Female     2848159264  489206.331845  5822
              Male       2908238731  494935.114193  5876
Married       Female     2907905003  499211.159313  5825
              Male       2960543673  503836.567903  5876
Separated     Female     1930823453  489435.602788  3945
              Male       1942938822  486099.279960  3997
Single        Female     1929569146  491609.973503  3925
              Male       2093746516  485900.792759  4309
Widowed       Female     1790152806  486322.414018  3681
              Male       2148857234  489712.222881  4388

### Combining filtering and aggregation into a single line

To perform both the filtering and aggregation in a single line, you can apply the boolean indexing directly to the DataFrame before calling `.groupby()`.

In [97]:
# Example: Groupby multiple dimensions, one measure, many aggregate functions, and row filter(s) in a single line
dimensions = ['MaritalStatus', 'Gender']
measures = ['CoverageAmount']

result_single_line = dfRaw[dfRaw['Age'] >= 25].groupby(dimensions)[measures].agg(['sum', 'mean', 'count'])
result_single_line

                     CoverageAmount
                                sum           mean count
MaritalStatus Gender
Divorced      Female     2848159264  489206.331845  5822
              Male       2908238731  494935.114193  5876
Married       Female     2907905003  499211.159313  5825
              Male       2960543673  503836.567903  5876
Separated     Female     1930823453  489435.602788  3945
              Male       1942938822  486099.279960  3997
Single        Female     1929569146  491609.973503  3925
              Male       2093746516  485900.792759  4309
Widowed       Female     1790152806  486322.414018  3681
              Male       2148857234  489712.222881  4388

In [98]:
# Let's play around a bit with dates
columns = ['CustomerID', 'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'EducationLevel', 'NewIncomeLevel', 'PolicyType', 'CoverageAmount', 'Qualification', 'PurchaseHistory']

dfRaw[columns].head()

,CustomerID,Age,AgeGroup,Gender,MaritalStatus,EducationLevel,NewIncomeLevel,PolicyType,CoverageAmount,Qualification,PurchaseHistory
0,84966,23,20s,Female,Married,Associate Degree,77595.1,Group,366603,HND,04-10-2018
1,95568,26,20s,Male,Widowed,Doctorate Degree,59584.8,Group,780236,PhD,11-06-2018
2,10544,29,20s,Female,Single,Associate Degree,81288.9,Group,773926,HND,06-05-2021
3,77033,20,20s,Male,Divorced,Bachelor's Degree,69719.1,Family,787815,BSc,09-02-2018
4,88160,25,20s,Female,Separated,Bachelor's Degree,42673.4,Family,366506,BSc,09-10-2018

In [99]:
dfRaw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53503 entries, 0 to 53502
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            53503 non-null  int64
 1   Age                   53503 non-null  int64
 2   Gender                53503 non-null  string
 3   MaritalStatus         53503 non-null  string
 4   EducationLevel        53503 non-null  string
 5   Location              53503 non-null  string
 6   Occupation            53503 non-null  string
 7   IncomeLevel           53503 non-null  int64
 8   BehavioralData        53503 non-null  string
 9   PurchaseHistory       53503 non-null  string
 10  CCChannel             53503 non-null  string
 11  PolicyOwned           53503 non-null  string
 12  CoverageAmount        53503 non-null  int64
 13  PremiumAmount         53503 non-null  int64
 14  PolicyType            53503 non-null  string
 15  CustomerPreferences   53503 non-null  string
 16  PreferredChannel      53503 non-null  string
 17  PreferredContactTime  53503 non-null  string
 18  PreferredLanguage     53503 non-null  string
 19  SegmentationGroup     53503 non-null  string
 20  NewIncomeLevel        53503 non-null  float64
 21  AgeGroup              53503 non-null  object
 22  Qualification         53503 non-null  object
dtypes: float64(1), int64(5), object(2), string(15)
memory usage: 9.4+ MB

In [100]:
# Convert PurchaseHistory column to a date column, handling mixed formats
dfRaw['PurchaseHistory'] = pd.to_datetime(dfRaw['PurchaseHistory'], format='mixed', dayfirst=False)
dfRaw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53503 entries, 0 to 53502
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            53503 non-null  int64
 1   Age                   53503 non-null  int64
 2   Gender                53503 non-null  string
 3   MaritalStatus         53503 non-null  string
 4   EducationLevel        53503 non-null  string
 5   Location              53503 non-null  string
 6   Occupation            53503 non-null  string
 7   IncomeLevel           53503 non-null  int64
 8   BehavioralData        53503 non-null  string
 9   PurchaseHistory       53503 non-null  datetime64[ns]
 10  CCChannel             53503 non-null  string
 11  PolicyOwned           53503 non-null  string
 12  CoverageAmount        53503 non-null  int64
 13  PremiumAmount         53503 non-null  int64
 14  PolicyType            53503 non-null  string
 15  CustomerPreferences   53503 non-null  string
 16  PreferredChannel      53503 non-null  string
 17  PreferredContactTime  53503 non-null  string
 18  PreferredLanguage     53503 non-null  string
 19  SegmentationGroup     53503 non-null  string
 20  NewIncomeLevel        53503 non-null  float64
 21  AgeGroup              53503 non-null  object
 22  Qualification         53503 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(5), object(2), string(14)
memory usage: 9.4+ MB

In [101]:
# Split PurchaseHistory column into 4 separate columns of day, month, quarter and year
dfRaw['PurchaseDay'] = dfRaw['PurchaseHistory'].dt.day
dfRaw['PurchaseMonth'] = dfRaw['PurchaseHistory'].dt.month
dfRaw['PurchaseQuarter'] = 'Q' + dfRaw['PurchaseHistory'].dt.quarter.astype(str)
dfRaw['PurchaseYear'] = dfRaw['PurchaseHistory'].dt.year

dfRaw.head()

,CustomerID,Age,Gender,MaritalStatus,EducationLevel,Location,Occupation,IncomeLevel,BehavioralData,PurchaseHistory,...,PreferredContactTime,PreferredLanguage,SegmentationGroup,NewIncomeLevel,AgeGroup,Qualification,PurchaseDay,PurchaseMonth,PurchaseQuarter,PurchaseYear
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,Policy-5,2018-04-10,...,Afternoon,English,Segment5,77595.1,20s,HND,10,4,Q2,2018
1,95568,26,Male,Widowed,Doctorate Degree,Goa,Manager,54168,Policy-5,2018-11-06,...,Morning,French,Segment5,59584.8,20s,PhD,6,11,Q4,2018
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,Policy-5,2021-06-05,...,Evening,German,Segment3,81288.9,20s,HND,5,6,Q2,2021
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,Policy-5,2018-09-02,...,Anytime,French,Segment3,69719.1,20s,BSc,2,9,Q3,2018
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,Policy-1,2018-09-10,...,Weekends,English,Segment2,42673.4,20s,BSc,10,9,Q3,2018